repos:
      - repo: https://github.com/timothycrosley/isort
        rev: 4.3.21
        hooks:
              - id: isort
      - repo: https://github.com/ambv/black
        rev: stable
        hooks:
              - id: black
      - repo: https://gitlab.com/pycqa/flake8
        rev: 3.7.7
        hooks:
              - id: flake8
      - repo: https://gitlab.com/pycqa/flake8
        rev: 3.7.7
        hooks:
              - id: flake8
                alias: flake8-cython
                name: flake8-cython
                args: ["--config=python/cudf/.flake8.cython"]
                types: [cython]
      - repo: local
        hooks:
              - id: clang-format
                name: clang-format
                description: Format files with ClangFormat.
                entry: clang-format -i
                language: system
                files: \.(cu|cuh|h|hpp|cpp)$
                args: ['-fallback-style=none']

default_language_version:
      python: python3
