dist: trusty
sudo: required
language: c++

branches:
    only:
        - master

matrix :
  include:
    - env: CUDA=8.0.61-1 PYTHON=3.6

before_install:
  - source ./travisci/install-cuda-trusty.sh
  # install miniconda
  - travis_retry wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=$HOME/miniconda3/bin:$PATH

install:
  # check
  - nvcc --version
  - conda --version
  # install conda build
  - conda install conda-build --yes
script:
  - conda build conda-recipes/libgdf --python=3.6 -c defaults -c conda-forge

