dist: trusty
sudo: required
language: cpp

branches:
    only:
        - master
env:
  global:
    secure: aNAYL4Upc0l+m1bU3S3fkiz5hLMWPAnRkAuO5zJ+8qoCanGuGthOGTTBnO8WwtD8G1L7n2opQ7xYKyW0oV+Ylv/vzmofVuOkVLcXrjGbeHe//Q06H+UkKyPMATTHR0cYIbMICOE5cNGVl8Zw3+i6yoLL5EQ/r65IWfPn0SxnJapPFCYwR9+p77u9d94Hw1tFdC3oqIVBnLsUl4q1eXQR+zDAFIRqjYyPGi3z014Vkqyy+sN5ysw4b8tIYCLqHl/YBb1ONFOo4+sG0RvxfxoyEk03LPvNYaYORUEvrXibPbkt3IkI3HGv690xLnI4JXheb7r//9rWCtSaOqnpGpnZQh4qjOOnY0Gtap3/FdBi8mITN6ytKsytTtBJ+Jhdzx1tHp4gFrrWJSEJGpHs2n5OneSDubFAQNEiwYX0K6K7A8R6a8JG6PTjvmZgVMrJ025gQoz4P9E2IRRhhyA0Z9tvEPnqaJUVdA06BK/ekKtW3+lECkNFvpB4WC9tK0WUzbw4PRNolfsr9ScmpzaFTpsv9HnYVcttgyoYylmmREpgCBCsQtmAHOARDFAXnLWtxIGKWciENVb40bwurXhKzqZ6QJbRoUpGFEkVTnHYnYv2qLK8zUm0toSagpA2hMxlppYgHtnWIRu1pW5HA7tK21BfH5tEW6IrQoDPjQSaLhboVzA=

matrix:
  include:
    - env: CUDA=8.0.61-1
    - env: CUDA=9.0.176_384.81
    - env: CUDA=9.1.85_387.26
    - env: CUDA=8.0.61-1 BUILD_CFFI=1 PYTHON=3.6
    - env: CUDA=8.0.61-1 BUILD_CFFI=1 PYTHON=3.5
    - env: CUDA=8.0.61-1 BUILD_CFFI=1 PYTHON=2.7

before_install:
  - source ./travisci/install-cuda-trusty.sh
  # install miniconda
  - travis_retry wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=$HOME/miniconda3/bin:$PATH

install:
  # check
  - nvcc --version
  - conda --version
  # install conda build
  - conda install conda-build anaconda-client --yes
  - conda install conda-build libboost --yes
script:
  # build ligdf
  - source ./travisci/build_libgdf.sh
  # build libgdf_cffi
  - source ./travisci/build_libgdf_cffi.sh

after_success:
  - source ./travisci/upload.sh

