# Copyright (c) 2018, NVIDIA CORPORATION.

# Usage:
#   conda build -c defaults -c conda-forge -c rapidsai .
{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') %}
{% set git_revision_count=environ.get('GIT_DESCRIBE_NUMBER', 0) %}
{% set cuda_version='.'.join(environ.get('CUDA', 'unknown').split('.')[:2]) %}
package:
  name: libgdf
  version: {{ version }}

source:
  # git_url: ../..
  path: ../..

build:
  number: {{ git_revision_count }}
  string: cuda{{ cuda_version }}_{{ git_revision_count }}
  script_env:
    - CC
    - CXX

requirements:
  # use channel:
  #   - defaults
  #   - conda-forge
  #   - rapidsai
  build:
    - cmake 3.12
  run:
    - pyarrow 0.10.*

test:
  commands:
    - test -f $PREFIX/include/gdf/gdf.h    # [unix or osx]
    - test -f $PREFIX/lib/libgdf.dylib     # [osx]

about:
  home: http://rapids.ai/
  license: Apache-2.0
  # license_file: LICENSE
  summary: cuDF-libgdf library
