name: pr

on:
  push:
    branches:
      - "pull-request/[0-9]+"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-builder:
    needs:
      - checks
      - changed_files
      - wheel-build-cudf
      - wheel-build-cudf-main
      - wheel-tests-cudf
      - wheel-build-dask-cudf
      - wheel-tests-dask-cudf
      - unit-tests-xdf
      - pandas-tests-xdf-main
      - pandas-tests-xdf-pr
      - pandas-tests-xdf-diff
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/pr-builder.yaml@branch-23.10
  checks:
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/checks.yaml@branch-23.10
    with:
      enable_check_generated_files: false
  changed_files:
    runs-on: ubuntu-latest
    name: Test changed files
    outputs:
      cudf_files_changed: ${{ steps.changed_files.outputs.cudf_files_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed files in cudf
        id: changed_files
        run: |
          git fetch origin branch-23.10-xdf
          diff=$(git diff --name-only origin/branch-23.10-xdf..HEAD python/cudf)
          if [ -n "$diff" ]; then
            has_changes='true'
          else
            has_changes='false'
          fi
          echo "Found changed: ${has_changes}"
          echo "cudf_files_changed=${has_changes}" >> "$GITHUB_OUTPUT"
  wheel-build-cudf:
    needs: checks
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/wheels-build.yaml@branch-23.10
    with:
      matrix_filter: map(select(.ARCH == "amd64" and .PY_VER == "3.10" and (.CUDA_VER == "11.8.0" or .CUDA_VER == "12.0.1")))
      build_type: pull-request
      script: "ci/build_wheel_cudf.sh"
  wheel-build-cudf-main:
    needs: checks
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/wheels-build.yaml@branch-23.10
    with:
      matrix_filter: map(select(.ARCH == "amd64" and .PY_VER == "3.10" and (.CUDA_VER == "11.8.0" or .CUDA_VER == "12.0.1")))
      build_type: pull-request
      script: "ci/build_wheel_cudf.sh main"
  wheel-tests-cudf:
    if: needs.changed_files.outputs.cudf_files_changed == 'true'
    needs: [wheel-build-cudf, changed_files]
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/wheels-test.yaml@branch-23.10
    with:
      matrix_filter: map(select(.ARCH == "amd64" and .PY_VER == "3.10" and (.CUDA_VER == "11.8.0" or .CUDA_VER == "12.0.1")))
      build_type: pull-request
      script: ci/test_wheel_cudf.sh
  wheel-build-dask-cudf:
    needs: wheel-tests-cudf
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/wheels-build.yaml@branch-23.10
    with:
      matrix_filter: map(select(.ARCH == "amd64" and .PY_VER == "3.10" and (.CUDA_VER == "11.8.0" or .CUDA_VER == "12.0.1")))
      build_type: pull-request
      script: "ci/build_wheel_dask_cudf.sh"
  wheel-tests-dask-cudf:
    needs: wheel-build-dask-cudf
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/wheels-test.yaml@branch-23.10
    with:
      matrix_filter: map(select(.ARCH == "amd64" and .PY_VER == "3.10" and (.CUDA_VER == "11.8.0" or .CUDA_VER == "12.0.1")))
      build_type: pull-request
      script: ci/test_wheel_dask_cudf.sh
  unit-tests-xdf:
    needs: [wheel-build-xdf, wheel-build-cudf]
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/wheels-test.yaml@branch-23.10
    with:
      matrix_filter: map(select(.ARCH == "amd64" and .PY_VER == "3.10" and (.CUDA_VER == "11.8.0" or .CUDA_VER == "12.0.1")))
      build_type: pull-request
      script: ci/xdf_scripts/run_tests.sh
  pandas-tests-xdf-main:
    # run the Pandas unit tests using xdf (main branch)
    needs: wheel-build-cudf-main
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/wheels-test.yaml@branch-23.10
    with:
      matrix_filter: map(select(.ARCH == "amd64")) | max_by(.CUDA_VER) | [.]
      build_type: pull-request
      script: ci/xdf_scripts/pandas-tests/run.sh main --transparent
  pandas-tests-xdf-pr:
    # run the Pandas unit tests using xdf (PR branch)
    needs: wheel-build-cudf
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/wheels-test.yaml@branch-23.10
    with:
      matrix_filter: map(select(.ARCH == "amd64")) | max_by(.CUDA_VER) | [.]
      build_type: pull-request
      script: ci/xdf_scripts/pandas-tests/run.sh pr --transparent
  pandas-tests-xdf-diff:
    # diff the results of running the Pandas unit tests and publish a job summary
    needs: [pandas-tests-xdf-main, pandas-tests-xdf-pr]
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/custom-job.yaml@branch-23.10
    with:
      node_type: cpu4
      build_type: pull-request
      run_script: ci/xdf_scripts/pandas-tests/diff.sh
