name: pr

on:
  push:
    branches:
      - "pull-request/[0-9]+"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-builder:
    needs:
      - checks
      - wheel-build-cudf
      - wheel-tests-cudf
      - wheel-build-dask-cudf
      - wheel-tests-dask-cudf
      - wheel-build-xdf
      - unit-tests-xdf
      - unit-tests-xdf-no-cudf
      - unit-tests-xdf-macos-windows
      - pandas-tests-xdf-main
      - pandas-tests-xdf-pr
      - pandas-tests-xdf-diff
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/pr-builder.yaml@branch-23.10
  checks:
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/checks.yaml@branch-23.10
    with:
      enable_check_generated_files: false
  wheel-build-cudf:
    needs: checks
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/wheels-build.yaml@branch-23.10
    with:
      matrix_filter: map(select(.ARCH == "amd64" and .PY_VER == "3.10" and (.CUDA_VER == "11.8.0" or .CUDA_VER == "12.0.1")))
      build_type: pull-request
      script: "ci/build_wheel_cudf.sh"
  wheel-tests-cudf:
    needs: wheel-build-cudf
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/wheels-test.yaml@branch-23.10
    with:
      matrix_filter: map(select(.ARCH == "amd64" and .PY_VER == "3.10" and (.CUDA_VER == "11.8.0" or .CUDA_VER == "12.0.1")))
      build_type: pull-request
      script: ci/test_wheel_cudf.sh
  wheel-build-dask-cudf:
    needs: wheel-tests-cudf
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/wheels-build.yaml@branch-23.10
    with:
      matrix_filter: map(select(.ARCH == "amd64" and .PY_VER == "3.10" and (.CUDA_VER == "11.8.0" or .CUDA_VER == "12.0.1")))
      build_type: pull-request
      script: "ci/build_wheel_dask_cudf.sh"
  wheel-tests-dask-cudf:
    needs: wheel-build-dask-cudf
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/wheels-test.yaml@branch-23.10
    with:
      matrix_filter: map(select(.ARCH == "amd64" and .PY_VER == "3.10" and (.CUDA_VER == "11.8.0" or .CUDA_VER == "12.0.1")))
      build_type: pull-request
      script: ci/test_wheel_dask_cudf.sh
  wheel-build-xdf:
    needs: checks
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/wheels-build.yaml@branch-23.10
    with:
      matrix_filter: map(select(.ARCH == "amd64" and .PY_VER == "3.10" and (.CUDA_VER == "11.8.0" or .CUDA_VER == "12.0.1")))
      build_type: pull-request
      script: ci/build_wheel_xdf.sh
  unit-tests-xdf:
    needs: wheel-build-xdf
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/wheels-test.yaml@branch-23.10
    with:
      matrix_filter: map(select(.ARCH == "amd64" and .PY_VER == "3.10" and (.CUDA_VER == "11.8.0" or .CUDA_VER == "12.0.1")))
      build_type: pull-request
      script: ci/xdf_scripts/run_tests.sh
  unit-tests-xdf-no-cudf:
    needs: wheel-build-xdf
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/wheels-test.yaml@branch-23.10
    with:
      matrix_filter: map(select(.ARCH == "amd64" and .PY_VER == "3.10" and (.CUDA_VER == "11.8.0" or .CUDA_VER == "12.0.1")))
      build_type: pull-request
      script: ci/xdf_scripts/run_tests.sh --no-cudf
  unit-tests-xdf-macos-windows:
    needs: checks
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        python-version: ["3.10"]
    runs-on: ${{ matrix.os }}
    name: ${{ format('{0} {1}', matrix.os, matrix.python-version) }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          cd python/xdf/
          python -m pip install .[test]
      - name: Run tests in normal mode
        run: |
          cd python/xdf/
          python -m pytest ./tests
      - name: Run tests in transparent mode
        run: |
          cd python/xdf/
          python -m pytest -p xdf.autoload ./tests
  pandas-tests-xdf-main:
    # run the Pandas unit tests using xdf (main branch)
    needs: wheel-build-xdf
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/wheels-test.yaml@branch-23.10
    with:
      matrix_filter: map(select(.ARCH == "amd64")) | max_by(.CUDA_VER) | [.]
      build_type: pull-request
      script: ci/xdf_scripts/pandas-tests/run.sh main --rewrite-imports
  pandas-tests-xdf-pr:
    # run the Pandas unit tests using xdf (PR branch)
    needs: wheel-build-xdf
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/wheels-test.yaml@branch-23.10
    with:
      matrix_filter: map(select(.ARCH == "amd64")) | max_by(.CUDA_VER) | [.]
      build_type: pull-request
      script: ci/xdf_scripts/pandas-tests/run.sh pr --rewrite-imports
  pandas-tests-xdf-diff:
    # diff the results of running the Pandas unit tests and publish a job summary
    needs: [pandas-tests-xdf-main, pandas-tests-xdf-pr]
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/custom-job.yaml@branch-23.10
    with:
      node_type: cpu4
      build_type: pull-request
      run_script: ci/xdf_scripts/pandas-tests/diff.sh
